### ISSUE TITLE
Option to have indication of if returned hash is a sampled hash or a full hash

### ISSUE THREAD

**Issue by mondjef** [kalafut/py-imohash#12]
I am using imohash to speed up a file deduplication process where I reduce the entire file set down to 'potential' duplicates using imohash then feed this into a secondary process where the 'potential' duplicates are verified using full hashes.  I know for a fact that imohash in many cases would be returning a full hash of the file when the files are small enough.  Knowing this, in my secondary process  I could bypass computing another hash for these particular files saving valuable time when running this process across 1000s of files.

Is this doable?

**Comment by kalafut** [comment]
Hi,

The threshold for full instead of sample is either specified by you (using `sample_threshold`) or defaults to 128K: https://github.com/kalafut/py-imohash/blob/305b6fb0fa102ba6441bf3fa4b76676a602f0900/imohash/imohash.py#L12 Since there is nothing dynamic about this, I think it is simplest for you to check the file size and if it's _less_ than the threshold, you know the full hash was used.

**Comment by mondjef** [comment]
Fair enough,  I guess my only hesitation in doing it as you suggest is any differences that might manifest between methods used to get file size.

**Comment by kalafut** [comment]
The first bytes of the hash are the [varint](https://pypi.org/project/varint/) encoded size, and you can decode them to get the size imohash is using. You can send the hash bytes (not hex string) into `varint.decode_bytes(hash)` and the result should be the file size.

**Comment by mondjef** [comment]
That looks like an elegant solution,  I'll give that a try.  Thanks!
