### ISSUE TITLE
hashfileobject sometimes raises OSError with io.StringIO

### ISSUE THREAD

**Issue by siligam** [kalafut/py-imohash#15]
`io.StringIO` does not support using negative indices for offsets.
This context is triggered when stream size exceeds imohash.SAMPLE_THRESHOLD size

Here is simple test to reproduce the issue

```python
>>> import io, string, imohash
>>> def test_io(data: str):
...     b = io.BytesIO(data.encode())
...     s = io.StringIO(data)
...     print("BytesIO", imohash.hashfileobject(b, hexdigest=True))
...     print("StringIO", imohash.hashfileobject(s, hexdigest=True))
...     return
>>> data = string.ascii_letters
>>> len(data) > imohash.SAMPLE_THRESHOLD
False
>>> test_io(data)
BytesIO 34144d8f582760d9d50582629f7eee67
StringIO 34144d8f582760d9d50582629f7eee67
>>> 
>>> # increasing the data volume to exceed SAMPLE_THRESHOLD size
>>> data = string.ascii_letters * 3000
>>> len(data) > imohash.SAMPLE_THRESHOLD
>>> True
>>> test_io(data)
BytesIO e0c2098806ccaccd4fc164056e182f42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in test_io
  File "/home/ps/repos/py-imohash/imohash/imohash.py", line 46, in hashfileobject
    f.seek(-sample_size, os.SEEK_END)
OSError: Can't do nonzero cur-relative seeks
```

**Comment by kalafut** [comment]
Hi. Thanks for bringing this up and the associated PR. My initial thought is that, if anything, the library is too lenient, and an exception should be thrown in your first case, too. The reason is that the semantics are only defined for bytes-like objects since the hash operates byte by byte. The encoding can't be assumed for Strings. You can see how things go wrong by passing an emoji into your `data` value and getting two different hashes. I've not looked closely enough to understand what happens when String data flows into the underlying `mmh` hash (it has to become bytes somehow).

Happy to hear your thoughts on this. ATM I'd lean towards documenting that bytes objects need to be used. If this was greenfield, I might even throw an exception for non-bytes, but I suspect that would break folks.

**Comment by siligam** [comment]
Hi Jim, thanks for the quick response.

I agree bytes are much cleaner to handle than Strings to overcome encoding related issues. I took a quick look at the underlying `mmh` hash library (https://github.com/hajimes/mmh3/tree/master?tab=readme-ov-file#simple-functions) and it appears that they do support both String and bytes. Their test suite also covers both.

Before enforcing only bytes objects as a requirement, consider the following strategy:

```python
try:
    f.seek(-sample_size, os.SEEK_END)
except OSError:
    import io
    if isinstance(f, io.StringIO):
        f.seek(size - sample_size)
    else:
        # we don't how to handle type(f)
        raise
```

I know the above code only covers the file seeking strategy depending on the stream and not the String encoding thing. I wonder if String encoding issues raise even before hitting this library. I really do not have a convincing argument to keep the support open for StringIO stream other than to say the underlying library supports it.

Please do as you see fit.

**Comment by kalafut** [comment]
Looking at the Python stdlib, I see that their [hashlib.file_digest](https://docs.python.org/3/library/hashlib.html#hashlib.file_digest) only accepts bytes objects. I tried hashing a `io.StringIO` and got:

```
ValueError: '<_io.StringIO object at 0x1030a77f0>' is not a file-like object in binary reading mode.
```

If anything, imohash is very much a file-centric hashing scheme, so I'm keen to leave things as they are. I will, however, add some comments to the README specifying that binary mode objects should be used. If there is a compelling case to work with strings directly I'm happy to revisit this.
